#!/bin/sh /etc/rc.common

START=29
STOP=11

USE_PROCD=1
BIN=/www/iot/broadcaster

start_service() {
    local enabled=$(uci get broadcaster.global.enabled 2>/dev/null || echo 0)
    [ "$enabled" -eq 0 ] && return

    local service=$(uci get broadcaster.global.service 2>/dev/null)
    local address=$(uci get broadcaster.global.address 2>/dev/null)
    local callback=$(uci get broadcaster.global.callback 2>/dev/null)

    procd_open_instance
    procd_set_param command $BIN
    [ -n "$service" ] && procd_append_param command -n "$service"
    [ -n "$address" ] && procd_append_param command -l "$address"
    [ -n "$callback" ] && procd_append_param command -x "$callback"
    procd_set_param respawn
    procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger broadcaster
}

reload_service() {
    stop
    start
}
