#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /www/iot/iot-provision
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}


reload_service() {
    procd_send_signal iot-provision
}
