#!/bin/sh /etc/rc.common

START=92
USE_PROCD=1
BIN=/www/iot/iot-agent

start_service() {

    local enabled=$(uci get agent.global.enabled 2>/dev/null || echo 0)
    [ "$enabled" -eq 0 ] && {
        echo "iot-agent disabled" >&2
        return
    }
    . /lib/functions/network.sh

    local interface=$(uci get agent.global.interface 2>/dev/null)
    local username=$(uci get agent.global.username 2>/dev/null)
    local password=$(uci get agent.global.password 2>/dev/null)
    local callback=$(uci get agent.global.callback 2>/dev/null)
    local proto=$(uci get agent.global.proto 2>/dev/null)
    local port=$(uci get agent.global.port 2>/dev/null)
    local controller=$(uci get agent.global.controller 2>/dev/null)

    local ifname
    [ -n "$interface" ] && network_get_device ifname "$interface"

    [ -z "$ifname" -a -z "$username" ] && {
        echo "You must specify an interface or username" >&2
        return
    }

    [ -z "$username" ] && {
        username=$(sed 's/://g' /sys/class/net/$ifname/address)
    }

    [ -z "$password" ] && password=$username

    [ -z "$proto" -o -z "$port" -o -z "$controller" ] && {
        echo "You must specify an server info" >&2
        return
    }

    procd_open_instance
    procd_set_param command $BIN -S $proto"://"$controller":"$port -u $username -p $password
    [ -n "$callback" ] && procd_append_param command -x "$callback"
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn 3600 5 86400
    procd_close_instance
}


reload_service() {
    procd_send_signal iot-agent
}