#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /www/iot/iot-mproxy -r iot-mproxy-chat -p "device/picoclaw/chat/request" -R "device/picoclaw/chat/response"
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_close_instance
}


reload_service() {
    procd_send_signal iot-mproxy
}
