#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /www/iot/iot-fsm -x /www/iot/handler/iot-fsm.lua -b 1 -e 10
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn 30 5 0
    procd_close_instance
}


reload_service() {
    procd_send_signal iot-fsm
}
