#!/bin/sh /etc/rc.common

START=92
STOP=99
USE_PROCD=1
BIN=/www/iot/iot-client

start_service() {

    procd_open_instance
    procd_set_param command $BIN
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn 3600 5 86400
    procd_close_instance

}